README.md

- Referred to Node v20, specifically, in the `README.md`
- Documented procedures for running tests and running linter
- Took a pass at refining the rest of the `README.md` from its boilerplate state

Refine boilerplate `README.md` and specify Node version

---

.prettierignore
README.md
package-lock.json
package.json
prettier.config.js

- Designate `prettier` as a development dependency
- Create `.prettierignore` and `prettier.config.js` files
- Configure Prettier to ignore the VS Code Extensions JSON file and the `ios` and `android` folders
- Document the usage of Prettier via `npm run format` and `npm run format:check`
You can configure PyCharm to use Prettier, like this:

Install and configure Prettier

---

.github/workflows/deploy.yml

Adding a simple workflow for building a deploying the website version of the app to GitHub Pages. I tend to like the [actions-based approach](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-with-a-custom-github-actions-workflow) (even though it's technically still in beta). I'm guessing this repo's Settings are set to the branch-based deployment, so we should change that just before merging this.
Later we should think about releases and building from tags, but while we're still in early days I think building from `main` is okay.

Add workflow for deploying to GitHub Pages

---

public/404.html

Currently, when a client navigates to a non-root URL of the web app via a means other than client-side routing (e.g. via reloading the web page or via typing the URL into the address bar); GitHub Pages displays an HTTP 404 Error Page. This phenomenon is described in #20.
GitHub Pages supports the use of custom `404.html` pages, which is what I am introducing with this branch. This custom `404.html` page does one thing: it redirects the client to the root URL of the site, discarding any path or query string they might have originally requested. I consider this to be an improvement over the current behavior.
> Note: The reason I didn't use the hard-coded relative URL of `/` to refer to the root URL of the site; is that I wanted to lay a foundation for moving to a more sophisticated …

Implement `404.html` page that redirects to domain root

---

.github/workflows/test.yml
src/App.tsx

This fixes the error that is happening when running `npm run build` (https://github.com/microbiomedata/nmdc-field-notes/actions/runs/7788383055/job/21237662321#step:5:32). I inadvertently introduced this error in #18. 
I also added a `npm run build` step to the main testing workflow so that we can catch this type of error in PRs instead of only when the deploy from `main` happens.

Fix top level await error on build

---

index.html
public/manifest.json

- I updated the `index.html` and `public/manifest.json` files to say "NMDC Field Notes" (or "Field Notes") instead of "Ionic App"

Replace boilerplate app name with real one

---

index.html
public/404.html
src/Router.tsx

- Implemented https://www.smashingmagazine.com/2016/08/sghpa-single-page-app-hack-github-pages/ (and added a check that the originally-requested URL and the site URL have the same origin; which is something `history.replaceState()` requires, but is not addressed in the article)
- Added a fallback route so that, when someone visits a path that doesn't exist in the app (such as `/foo`), the app redirects them to the root path

Support deep linking on GitHub Pages

---

src/pages/WelcomePage/WelcomePage.css
src/pages/WelcomePage/WelcomePage.tsx

- Removed all inline `style` attributes from the `WelcomePage` component
- Instead, used CSS classes—either Ionic ones (if available) or ad hoc ones (if the former were not available)

Convert inline styles into (Ionic or ad hoc) CSS classes

---

public/.well-known/README.md
public/.well-known/apple-app-site-association
public/.well-known/assetlinks.json

In this branch, I created two files:
- `apple-app-site-association`
- `assetlinks.json`
The first one will be used for Apple (iOS) universal links.
The second one will be used for Android universal links.
Both files are in `public/.well-known/`, so they will be included as-is in the build that gets deployed to GitHub Pages.
I also created a `README.md` file in the same directory. That file contains documentation about the directory and its contents.
---
While these changes tackle part of https://github.com/microbiomedata/nmdc-field-notes/issues/28, they do not tackle the entire ticket. Therefore, if GitHub automatically closes that ticket when this gets merged in, I will reopen the ticket.

Create universal link-related files in `public` folder

---

android/app/src/main/AndroidManifest.xml

In this branch, I updated the `AndroidManifest.xml` file—as instructed in the [Ionic docs](https://capacitorjs.com/docs/guides/deep-links#add-intent-filter) about universal links—so that the Android app would recognize incoming links.

Configure Android app to recognize incoming links

---

src/Router.tsx
src/components/StudyList/StudyList.tsx
src/components/TabNavigator/TabNavigator.tsx
src/pages/PlaceholderPage.tsx

In this branch, I implemented tab-based navigation.
There are 3 tabs: 
- Studies
- Guide
- Settings
The `TabNavigator` component renders a horizontal bar containing those tabs; and also renders a router outlet for all routes that are "within" the tabbed section of the app. All such routes share a common route prefix (I arbitrarily set it to `/in`), which is matched by an application-level route that renders the `TabNavigator`, itself.
I also introduced `PlaceholderPage`, a temporary component we can use when we want an `IonPage` containing some basic content, in order to demonstrate functionality (e.g. a target to route to).
I also updated some relatively hard-coded paths I came across so that they use the common `PATHS` object instead. On a side note, I saw that there is a [draft …

Implement tab-based navigation

---

ios/App/App.xcodeproj/project.pbxproj
ios/App/App/App.entitlements

The changes in this branch were generated by Xcode when I [used the Xcode GUI](https://capacitorjs.com/docs/guides/deep-links#add-associated-domain) to configure the iOS app to have `fieldnotes.microbiomedata.org` as one of its "Associated Domains".
I think committing these changes to the repository will make it so other developers don't have to do the same configuration in the Xcode GUI.
This is the final piece of #28. When this branch gets merged in, I will close that issue.

Configure iOS app to recognize incoming links

---

README.md
src/api.ts
src/config.ts
src/mocks/server.ts
src/pages/LoginPage/LoginPage.tsx
src/pages/WelcomePage/WelcomePage.tsx

In this branch, I introduced a layer of abstraction between the `import.meta.env` object and the rest of the application code. The new layer provides type information, documentation, and default values. It could also provide validation/sanitization/transformation in the future. I think the introduction of this new layer will make it easier for people to work on application code, as IDEs can now validate the (names and types of) ~environment variables~ "config variables" referenced by the application code.
Here's a pair of diagrams showing the "before" and "after" architecture (except that I accidentally depicted the new `config.ts` file as being outside of the application code, whereas it is part of the application code in reality).

Decouple application code from environment variables

---

package-lock.json
package.json
src/api.test.ts
src/api.ts
src/components/StudyForm/StudyForm.module.css
src/components/StudyForm/StudyForm.tsx
src/data.ts
src/global.d.ts
src/mocks/fixtures.ts
src/mocks/server.ts
src/pages/StudyCreatePage/StudyCreatePage.tsx
src/pages/StudyEditPage/StudyEditPage.tsx
src/queries.test.tsx
src/queries.ts

Fixes #45 
These changes fill out the stub study create and study edit pages with real content. They both present a common study form component with basic validation. The edit page also includes a dropdown menu in the toolbar to initiate deleting a study.
* Add new dependency on [`react-hook-form`](https://react-hook-form.com/). I think most people have seen this library before (maybe?), so hopefully it doesn't need too much explanation. But this library provides form state management and validation. 
* Add methods to the `nmdc-server` client in `src/api.ts` for calling the `POST /api/metadata_submission` and `DELETE /api/metadata_submission/:id` endpoints. Since the `DELETE` endpoint returns a 204 response with an empty body I shuffled around the protected methods of `FetchClient` to …

Implement study edit and create screens

---

package-lock.json
package.json
src/components/Tutorial/Tutorial.tsx
src/components/Tutorial/md-in-js/001.md.ts
src/components/Tutorial/md-in-js/002.md.ts
src/components/Tutorial/md-in-js/003.md.ts
src/components/Tutorial/md-in-js/004.md.ts
src/components/Tutorial/md-in-js/005.md.ts
src/components/Tutorial/md-in-js/index.ts

**Note: The base branch in this PR is not `main`.**
In this branch, I demonstrate an approach that involves defining the tutorial content in Markdown format (which I'm under the impression its primary maintainers prefer) and having the React components load it from there and render it on the web page. I tried to deviate as little as possible from the existing code in the base branch (i.e. `#48-tutorial-screen`), focusing only on the aforementioned demonstration.
Here's a screenshot showing the rendered output:
> The rendered output is pretty much the same as in the "base" branch, except for a few minor differences due to the tags/components I opted to use instead.

Demonstrate "Markdown-in-JS" approach (using `react-markdown`)

---

src/components/Tutorial/Tutorial.tsx

In this branch, I fixed a layout bug causing text in a Markdown-powered list item to touch the hyperlink that followed it. The fix involved wrapping the list item's content in a `<span></span>` element. As a side effect, I was able to remove an obsolete (and unnecessarily restrictive) type hint.
Example list item (Markdown):
```diff
const rawMarkdownContent = `
+ - Link to [example.com](https://www.example.com)
- Way of measuring sampling depth e.g., ruler, measurement device
```
Here's how that list item is rendered when using the code in `main` today:
Here's how that list item is rendered when using the code in this PR branch:

Fix layout bug where hyperlink touches preceding text

---

src/Validator.ts
src/api.ts
src/components/SampleList/SampleList.tsx
src/components/StudyView/StudyView.tsx
src/mocks/fixtures.ts
src/pages/SamplePage/SamplePage.tsx
src/utils.ts

Fixes #67 
Primarily this PR is about adding the ability to delete samples. This is implemented in `src/pages/SamplePage/SamplePage.tsx` similar to the way the delete study functionality works. However, in testing that functionality, I uncovered two bugs that I'm also addressing here.
First, I realized it was a mistake on my part to inject the `_index` field at the API layer. The only place it is really needed is in the `SampleList` component in order to keep sample indexes straight while filtering them. The downside of injecting the `_index` field way upstream in the API access methods is that it becomes part of the data that is sent back to the server when updating a sample. This, in an of itself, is not desirable since `_index` is a UI-only concern. But it also caused some confusion …

Add ability to delete samples

---

src/components/StudyView/StudyView.tsx
src/utils.ts

Fixes #74 
When a new submission is created it looks (in part) like:
```js
{
...
metadata_submission: {
...
sampleData: { }
}
}
```
The existing logic of `getSubmissionSamples` would look for a field like `soil_data` in the `sampleData` object and if it wasn't there (as in the above case) then it would return a new empty array. This works fine for cases where the `sampleData` needs to be _displayed_. However when the `sampleData` is being _modified_ we need to ensure that the (for example) `soil_data` field is present in `sampleData` and set it to an empty array if it wasn't previously there.
The fix here to add an `options` parameter to `getSubmissionSamples` with a `createSampleDataFieldIfMissing` field. We set that field to `true` when creating new samples.

Add option to getSubmissionSamples to allow creating missing sampleData fields when necessary

---

README.md
src/pages/SettingsPage/SettingsPage.tsx

In this branch, I fixed the vertical alignment of the version number on the "Settings" screen (on Android/MD devices). It was already correct on iOS devices.
Before:
After:
I also updated `README.md` so that it explicitly lists the query string developers can use to force the styles to be Android/MD, in an attempt to facilitate testing with both styles in the future.

Fix vertical alignment of version number on "Settings" screen (on Android/MD)

---

.github/workflows/test.yml
README.md
package-lock.json
package.json
src/Router.tsx
src/components/AuthRoute/AuthRoute.tsx
src/components/SampleList/SampleList.tsx
src/components/StudyList/StudyList.tsx
src/components/StudyView/StudyView.tsx
src/components/TabNavigator/TabNavigator.tsx
src/pages/LogoutPage/LogoutPage.tsx
src/pages/SamplePage/SamplePage.tsx
src/pages/StudyCreatePage/StudyCreatePage.tsx
src/pages/StudyEditPage/StudyEditPage.tsx
src/pages/StudyViewPage/StudyViewPage.tsx
src/pages/TokenPage/TokenPage.tsx
src/pages/WelcomePage/WelcomePage.tsx
src/paths.ts

Fixes #115 
These changes add a dependency on the [`madge`](https://github.com/pahen/madge) package and connect it to a new `check.imports` script in `package.json`. The script is now called in the tests workflow to ensure we don't introduce new circular dependencies. In #115 I talked about using [`dpdm`](https://github.com/acrazing/dpdm), but I realized after making the issues that `madge` seems to be more popular and has more people working on it. 
As far as fixing the existing circular imports, all of them looked something like this:
```mermaid
flowchart LR
A(Router.tsx)
A --> B(various pages & components)
B --> A
```
Where the various pages & components were importing `Router.tsx` to get the `paths` object.
So the fix is to move the `paths` object to a separate module and you end up …

Install `madge` NPM package and eliminate circular dependencies

---

ios/App/App/Info.plist

In this branch, I configured the iOS app so that the text below the icon on the iOS home screen  says "Field Notes" (the app icon already says "nmdc" on it) instead of "NMDCFieldNot...".
iOS seems to me to impose a 15-character limit on this string. Optionally, see the comments in #124 for details.
Before:
After:

Shorten iOS app icon text to "Field Notes" to avoid ellipses

---

src/components/StudyForm/StudyForm.tsx

In this branch, I added buttons on the right sides of two text inputs on the "Create Study" screen:
- Principal Investigator > Name
- Principal Investigator > ORCID iD
The buttons are only rendered when the user is logged in (so, if we end up allowing logged-out users to snoop around the UI, these buttons will not appear to them).
When the user clicks a button, the app will update the field so it contains the associated value from the user's own ORCID account. For example, if the user clicks the button on the "Name" field, the app will update the "Name" field so it contains the user's name.
When the field already contains the value that clicking the button would cause the field to have, the button is disabled.
Here's a brief screencast of the buttons in action (with personal information …

Allow user to populate Study PI Name and ORCID iD with user's own info

---

src/api.ts
src/data.ts
src/mocks/fixtures.ts

Fixes #128 
This is a follow-on to https://github.com/microbiomedata/nmdc-server/pull/1300.
When a new submission is generated by the Field Notes app (`src/data.ts`), set the `source_client` field to `field_notes`. 
I made one of the mock submissions used in tests (`src/mocks/fixtures.ts`) have a `source_client` of `submission_portal` just to ensure that we don't do anything with the `source_client` field that implicitly assumes a value of `field_notes` coming _from_ the backend.

Set source_client to field_notes when generating new submission

---

ios/App/App.xcodeproj/project.pbxproj
public/.well-known/apple-app-site-association

Today, I deleted the NMDC Field Notes app identifier from the "ENT" Apple Developer account and created an NMDC Field Notes app identifier in the non-"ENT" Apple Developer account. The reason I first deleted it from the "ENT" account is so that I could use the same Bundle ID in the non-"ENT" account. The actions I took are documented in [this Issue comment](https://github.com/microbiomedata/nmdc-field-notes/issues/135#issuecomment-2249553410).
In this PR branch, I have updated all references to the Team ID so that, instead of referring to the Team corresponding to the "ENT" account (where our app identifier no longer exists), they refer to the Team corresponding to the non-"ENT" account (where our app identifier now exists).
Since I'll be out Friday, and given the specific changes …

Replace Apple Developer "ENT" Team ID with non-"ENT" Team ID

---

ios/App/App.xcodeproj/project.pbxproj

In this branch, I made two changes in preparation for publishing the iOS app to TestFlight. 
Those changes were:
- Specify an app category (I chose "Productivity")
- Update the user-facing iOS app version number to match what's in `package.json`
This PR branch is the one I used to build and publish an app to TestFlight.

Specify Apple app category and make iOS app version match `package.json` version

---

capacitor.config.ts

Fixes #119 
Despite what this issue says, we didn't really need _true_ separate environments as outlined in https://capacitorjs.com/docs/guides/environment-specific-configurations. What's written there would be necessary for controlling things like app IDs or custom URI schemes by environment. For simply enabling/disabling cleartext HTTP requests we just needed to set the `cleartext` value based on `NODE_ENV`. 
I believe this only affects Android devices, so with `VITE_NMDC_SERVER_API_URL=http://127.0.0.1:8000` (with a local `nmdc-server` instance running) the app should behave normally when running:
```
npm run sim.android
```
However it should _not_ work when running:
```
NODE_ENV=production npm run sim.android
```
This is also a good reminder that we should explicitly set the …

Allow cleartext HTTP requests only in non-production builds

---

src/api.ts
src/pages/StudyEditPage/StudyEditPage.tsx
src/queries.ts

This fixes a bug that Montana just reported to me that I had already fixed in a development branch for #42. That branch isn't quite ready for a PR, so I'm just cherry picking a couple of commits out of it.
The issue was introduced in #137, and the problem has to do with attempting to mutate an existing object in order to add the `permissions` field instead of using `produce` to perform the mutation.
Since this is a fairly egregious bug that prevents updating submissions we should produce and distribute new iOS and Android builds after this is merged in.

Fix permissions update

---

.env.production
.env.staging
.github/workflows/release.yml
README.md
android/.gitignore
package-lock.json
package.json
trapeze.config.yaml

Fixes #148 
These changes add a section to the README about making and distributing releases. They also add a bit of automation to eliminate a few manual steps -- although there are still plenty of them 😬.
In other projects we initiate the release process by creating a GitHub Release. This one is kind of the inverse. Because of the updates that need to be made to `package.json` and various native project files (in the `android` and `ios` directories), it turns out to be simpler to create those changes _locally_ and automatically create the GitHub Release when those local changes are pushed to GitHub.
At a high level the process looks like this:
1. Use the `npm version` command to update `package.json` and create a new version tag. 
* The new `version` script in `package.json` introduced …

Document and further automate the release process

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/config.yml

In this branch, I created an issue template.
Since I created it as a YAML file, GitHub will display it as a **form** that the person creating the issue can fill in, in order to provide information to us. However, the person still has the option to create an issue the old-fashioned way (i.e. without a template) instead. In other words, this PR _adds_ an option—it doesn't take away any options.
You can preview this form in the following temporary repository in my personal GitHub account. You can create issues there (I'll eventually delete them, along with the repository, itself).
Temporary repository: https://github.com/eecavanna/delete-me-repo/issues/new/choose

Configure GitHub to display bug report form (issue template)

---

src/components/Checklist/Checklist.module.css

Update .listItem in Checklist.module.css: remove 'color: black'

Fix 'Guide' dark mode issue

---

.github/workflows/release.yml
README.md
package-lock.json
package.json
scripts/release.sh
src/components/SettingsAboutList/SettingsAboutList.tsx
src/config.ts
src/vite-env.d.ts
trapeze.config.yaml
vite.config.ts

Fixes #159 
As mentioned [here](https://github.com/microbiomedata/nmdc-field-notes/issues/159#issuecomment-2302571188) the proximate cause of the version number not appearing in the Settings tab was that we were implicitly relying on an environment variable only set when running NPM scripts. And the release instructions were written to _not_ use NPM scripts.
Another wrinkle is that the release instructions were mainly focused on the _version_ number. But we learned in our first go at following the instructions in earnest that the _build_ number is also an important consideration. Sometimes we will _only_ want to increment the build number without updating the version number.
* Previously the source of truth for the build number was _two_ native project files (`android/app/build.gradle` …

Rework release process to account for version and build numbers

---

.github/workflows/deploy.yml
src/components/DevelopmentSiteWarning/DevelopmentSiteWarning.tsx
src/components/ThemedToolbar/ThemedToolbar.tsx
src/config.ts
src/pages/WelcomePage/WelcomePage.tsx

Fixes #166 
This is just a quick 'n' dirty change to show a warning banner on the GH Pages site. The goal is to warn people about using it while we decide its ultimate fate (#167).
A new environment variable controls whether the warning banner is shown or not. The environment variable does _not_ get set in any of the existing `.env.*` files. Rather it just gets set as the site is built in the GH Pages deploy workflow.

Add dev site warning banner; display it on GH Pages site

---

src/App.tsx
src/api.ts
src/components/DataPrefetcher/DataPrefetcher.tsx
src/pages/SamplePage/SamplePage.tsx
src/queries.ts

Fixes #155 
Fixes #156 
These changes fix two related issues around when and how the submission schema is fetched. The goals are:
* Prefetch the schema _before_ it is needed to prevent certain bad situations while offline. In the event that the schema is still not available when it is needed, show an error message.
* Only fetch the schema when a new version is available.
Previously the schema information was fetched at the time it was needed via the `useSubmissionSchema` hook call in the `SamplePage` component. The hook is still called there, but now the data it provides is prefetched via a new `DataPrefetcher` component placed near the top-level of the app. See the [TanStack Query docs](https://tanstack.com/query/v5/docs/framework/react/guides/prefetching) for details on their …

Schema fetching and caching

---

.env.local.example
.env.production
.env.staging
src/components/Checklist/md-in-js/fieldwork-003.md.ts
src/components/Checklist/md-in-js/util.tsx
src/config.ts
src/vite-env.d.ts

Generate schemas Markdown from the TEMPLATES instead of hardcoding a list of schemas.

Generate template list (Markdown) from the existing `TEMPLATES` object

---

scripts/release.sh

Fixes https://github.com/microbiomedata/nmdc-field-notes/issues/182
As pointed out in the issue, there is a `prerelease` script which runs `npm run build.native` before running the `release.sh` script:
https://github.com/microbiomedata/nmdc-field-notes/blob/d862c821a1a696b0c217b1a55b39d3599108016c/package.json#L24-L25
The purpose of that build is to ensure that we didn't accidentally forget to sync the native projects and commit those changes before making a release (`release.sh` will stop if there are uncommitted changes leftover from that build). We still want to do that, so I've kept that in place.
However, we do need _another_ build _after_ the new build/version numbers are set. This allows the new numbers to be baked into the web assets that the native projects use. I've added that …

Run ionic build after trapeze in release script

---

src/components/SampleSlotEditModal/SampleSlotEditModal.test.ts
src/components/SampleSlotEditModal/SampleSlotEditModal.tsx

Fixes #176 
These changes update the helper method (`getSelectState`) in `src/components/SampleSlotEditModal/SampleSlotEditModal.tsx` which determines whether to show a select box or a plain text box for a given slot. Previously the logic only looked at the slot's `range`. That's sufficient most of the time, but there are a few slots that (mainly for historical reasons) allow either a string _or_ an enum (via the `any_of` slot attribute). Previously `getSelectState` would return `isSelectable: false` in that case. Now it will return `isSelectable: true` and the appropriate permissible values.

Check `any_of` on slot definition when determining input type

---

src/api.ts
src/components/StudyForm/StudyForm.tsx

Fixes #198 
Previously the Name and ORCID iD fields of the Study form individually had autofill buttons. These changes replace those two buttons with a single autofill button.
This also includes minor changes to make padding and margins more uniform in the Study form.
Additionally, with the changes in https://github.com/microbiomedata/nmdc-server/pull/1442, the backend now associates an optional email address with User records. These changes also add the `email` field to the app's User model. If the `email` field of the logged in user is present and populated, it will be used to fill out the Study form's email field when the autofill button is pressed. 
| Before Clicking | After Clicking |
| --- | --- |
| <img width="435" alt="image" …

Replace individual autofill buttons on name and ORCID with single button

---

src/Router.tsx
src/api.ts
src/components/SampleList/SampleList.module.css
src/components/SampleList/SampleList.tsx
src/components/SampleView/SampleView.tsx
src/components/StudyForm/StudyForm.tsx
src/components/StudyList/StudyList.tsx
src/components/StudyView/StudyView.tsx
src/data.ts
src/pages/SamplePage/SamplePage.tsx
src/pages/StudyCreatePage/StudyCreatePage.tsx
src/pages/StudyViewPage/StudyViewPage.tsx
src/paths.ts
src/utils.ts

Fixes #177 
These changes add support for selecting multiple environmental templates. This is enabled by backend support provided by https://github.com/microbiomedata/nmdc-server/pull/1372 and https://github.com/microbiomedata/nmdc-server/pull/1491.
Because we can't 100% control the timing of the app's release relative to the backend's release, the overall approach of these changes is to make the app agnostic to the `packageName` field being a single string (the old single template format) _or_ an array of strings (the new multiple template format).
The one thing that the app can't know _a priori_ is whether it should send a single string or an array of strings when creating a new submission (if you're working with an existing submission the app will just keep whatever it was given -- …

Add support for multiple environmental templates

---

README.md

On this branch, I added a section to the "Visit development server" section of `README.md`. The new section contains instructions people can follow to temporarily hide the ReadQueryDevtools icon from the UI.
Fixes #204

Add instructions for hiding the ReactQueryDevtools icon

---

src/components/StudyForm/StudyForm.tsx
src/data.ts
src/theme/variables.css

Now that Release 2024.12 is on production, these changes complete the corresponding app changes by enabling multiple environment selection for new studies.
I also made a small unrelated tweak to the theme stylesheet so that list items don't have an award gray background on Android in dark mode. These changes ensure that list items always have the same background color as the main interface no matter what platform or light/dark mode.

Enable multiple templates by default

---

public/.well-known/assetlinks.json

The Google Play Console was complaining that it could not verify domain ownership for deep linking. Its suggested fix was to add this additional certificate fingerprint to our `assetlinks.json` file. So that's what I'm doing here 😂

Add additional certificate fingerprint

---

src/pages/WelcomePage/WelcomePage.tsx

Fixes #183 
On this branch, I simplified the "Welcome" screen of the app.
On this branch, I made the following changes to the "Welcome" screen of the app, in an attempt to make it consistent with the functionality the app has today.
1. **The "Take a tour" link**: I replaced the "Take a tour" link with a "Learn more" link that points somewhere else.
- The "Learn more" link points to a page about the NMDC Field Notes app, on the WordPress website (i.e., this page: https://microbiomedata.org/field-notes/).
2. **The "Checklist" card**: I removed the "Checklist" card entirely.
- As @pkalita-lbl pointed out in [this comment](https://github.com/microbiomedata/nmdc-field-notes/issues/183#issuecomment-2455437070), the same checklist is already accessible from other screens of the app (e.g., the …

Simplify "Welcome" screen (remove obsolete items and spread others out)

---

src/components/AppTourProvider/AppTourProvider.tsx

On this branch, I made two changes:
1. Update the color of the navigation dots in the tour popup, so they use the app theme's primary color (instead of the NPM package's default color, which was a different shade of blue)
2. Update the "Dismiss" button on the final step of the tour, so it matches the other buttons in the app (specifically, so its background color is the app theme's primary color)
Here are before-and-after screenshots:
- Left: iOS
- Right: Android
> I think I didn't notice the dot's blue shade before because the app theme's primary color was not present in the popup (out of sight, out of mind).
> I think I didn't notice the dot's blue shade before because the app theme's primary color was not present in the popup (out of sight, out of mind).
- Left: iOS
- Right: Android

Update tour navigation dots and button to use theme's primary color

---

src/components/AppTourProvider/hooks.ts
src/components/SampleList/SampleList.test.tsx
src/components/SampleList/SampleList.tsx
src/components/StudyView/StudyView.tsx

Fixes #231 
The `StudyView` component conditionally launches on modal on data fetch. If it (or any components that it renders) starts a tour on view enter and the modal is opened soon after when the data fetch settles, the result is a tour highlighting an element that is hidden under the modal.
These changes address this by:
* Adding a prop to the `useAppTour` hook that allows a client to turn off initiating the tour on view enter
* Adding a return value from `useAppTour` that includes a function which can imperatively start the tour (or at least attempt to, depending on whether the tour has already been presented)
* Use an extra bit of state in `StudyView` to control whether it is safe to present tours. `StudyView` and its children can observe this state to imperatively start a tour when …

Let tours be skipped on view enter and started later imperatively

---

README.md

On this branch, I updated the release documentation so it includes instructions for publishing the Android build to Google Play via the Google Play Console. The rendered version of the updated release documentation (i.e. the version on this branch) is [here](https://github.com/microbiomedata/nmdc-field-notes/blob/235-update-release-documentation-to-account-for-google-play-console/README.md#make-a-release).

Document process of publishing Android build to Google Play

---

android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml

Fixes #238
I can't say I truly understand what these changes are doing. I'm just following the workaround provided in https://github.com/ionic-team/capacitor-assets/issues/522. 
See #238 for the before. Here's the after:
So it seems to work, and I didn't see any other adverse effects.

Update icon inset to remove unsightly gap

---

src/components/SettingsAboutList/SettingsAboutList.tsx
src/components/TourVisibilityManager/TourVisibilityManager.tsx
src/config.ts

Fixes #242 
These changes add a "Contact us" item to the Settings tab. I confirmed that a `mailto:` link does open the default email app (GMail) on an Android simulator. iOS simulators [do not provide an email app](https://discussions.apple.com/thread/3830910?answerId=17959704022&sortBy=rank#17959704022); I trust it will work there as well but we'd need to test on a physical device.
I also changed the existing "Reset tours" item to the default color (it was the primary color). I think the intention was to show that that item was clickable. But we also had other interactive items that were _not_ the primary color. We'll always have a mix of interactive and non-interactive items, but I think I'd rather just be consistent with the colors.
Finally I updated the default value for the support …

Add contact item to Settings tab

---

src/components/SlotSelectorModal/SlotSelectorModal.tsx
src/components/StudyView/StudyView.tsx

Fixes #246 
The infinite loop of opening and closing the modal was caused by a bad interaction between the `useEffect` callback that attempts to open the modal when there are templates missing field visibility settings and the `onSuccess` callback called after the submission was updated with new field visibility settings that closes the modal. I believe the order of the `useEffect` call and the `onSuccess` call is not 100% deterministic, which is why there was initially a little confusion about how to reproduce the issue.
The fix here is to remove the `onSuccess` callback entirely. With these changes the `useEffect` callback is responsible for both opening _and_ closing the slot selector modal entirely based on the server data state. There is an added benefit here that the modal will now …

Fix slot selector modal presentation logic

---

src/pages/GuidePage/md/guide-page.md

On this branch, I added a bullet point to the "Basic recommendations for fieldwork" section of the "Guide" screen (that is the section that already contained things like "Bring sunscreen..." and "Bring a battery pack..."). The new bullet point says:
- Bring a stylus in case you want to use a touchscreen while wearing gloves.
In the bullet point, I mentioned gloves as an example use case. In reality, a stylus can be used without gloves also (e.g. when one's hands are wet or dirty).

Recommend bringing a stylus into the field (fixes #249)

---

README.md

On this branch, I updated the developer documentation in `README.md` so it includes a (collapsed-by-default) section about setting up the `adb` command.
Fixes https://github.com/microbiomedata/nmdc-field-notes/issues/243

Add instructions for enabling `adb` command in shell

---

src/api.ts
src/components/StudyForm/StudyForm.tsx
src/data.ts
src/mocks/fixtures.ts
src/utils.ts

Fixes #255 
* Align the Typescript definitions of the submission data format with the [backend data model](https://github.com/microbiomedata/nmdc-server/blob/main/nmdc_server/schemas_submission.py).
* Remove some old workaround to allow the `packageName` field to either be a single string or an array of strings. This value is always an array of strings now.

Align submission data model with backend
